pub trait RlVector3 {
    fn zero() -> Self;
    fn one() -> Self;
    fn add(&self, v2: Self) -> Self;
    fn add_value(&self, add: f32) -> Self;
    fn subtract(&self, v2: Self) -> Self;
    fn subtract_value(&self, sub: f32) -> Self;
    fn scale(&self, scalar: f32) -> Self;
    fn multiply(&self, v2: Self) -> Self;
    fn cross_product(&self, v2: Self) -> Self;
    fn perpendicular(&self) -> Self;
    fn length(&self) -> f32;
    fn length_sqr(&self) -> f32;
    fn dot_product(&self, v2: Self) -> f32;
    fn distance(&self, v2: Self) -> f32;
    fn distance_sqr(&self, v2: Self) -> f32;
    fn angle(&self, v2: Self) -> f32;
    fn negate(&self) -> Self;
    fn divide(&self, v2: Self) -> Self;
    fn normalize(&self) -> Self;
    fn project(&self, v2: Self) -> Self;
    fn reject(&self, v2: Self) -> Self;
    fn ortho_normalize(v1: &mut Self, v2: &mut Self);
    fn transform(&self, mat: impl super::RlMatrix) -> Self;
    fn rotate_by_quaternion(&self, q: impl super::RlQuaternion) -> Self;
    fn rotate_by_axis_angle(&self, axis: Self, angle: f32) -> Self;
    fn move_towards(&self, target: Self, max_distance: f32) -> Self;
    fn lerp(&self, v2: Self, amount: f32) -> Self;
    fn cubic_hermite(&self, tangent1: Self, v2: Self, tangent2: Self, amount: f32) -> Self;
    fn reflect(&self, normal: Self) -> Self;
    fn min(&self, v2: Self) -> Self;
    fn max(&self, v2: Self) -> Self;
    fn barycenter(p: Self, a: Self, b: Self, c: Self) -> Self;
    fn unproject(&self, projection: impl super::RlMatrix, view: impl super::RlMatrix) -> Self;
    fn to_float_v(&self) -> crate::ffi::raymath::float3;
    fn invert(&self) -> Self;
    fn clamp(&self, min: Self, max: Self) -> Self;
    fn clamp_value(&self, min: f32, max: f32) -> Self;
    fn equals(&self, q: Self) -> i32;
    fn refract(&self, n: Self, r: f32) -> Self;
}
